"""empty message

Revision ID: 69e0378083a2
Revises: a335894c2159
Create Date: 2016-05-14 22:30:37.959238

"""

# revision identifiers, used by Alembic.
revision = '69e0378083a2'
down_revision = 'a335894c2159'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
