"""empty message

Revision ID: cef857b35fac
Revises: 69e0378083a2
Create Date: 2016-05-15 08:42:50.241040

"""

# revision identifiers, used by Alembic.
revision = 'cef857b35fac'
down_revision = '69e0378083a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
