"""empty message

Revision ID: cfb1ec991290
Revises: cef857b35fac
Create Date: 2016-05-16 11:51:45.933282

"""

# revision identifiers, used by Alembic.
revision = 'cfb1ec991290'
down_revision = 'cef857b35fac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
